<a href="https://colab.research.google.com/github/BrunaBitencourt05/techstore-analise-vendas/blob/main/techstore_analise_vendas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df_vendas = pd.read_csv("/content/vendas.csv")

In [3]:
df_vendas.head()

,data,produto,categoria,quantidade,preco_unitario,cliente,regiao
0,2025-12-09,Headset G,Periféricos,1,2759,Fernanda,Sudeste
1,2025-03-12,Armário P,Móveis,2,4516,Rafael,Norte
2,2025-11-24,Mesa Escritório N,Móveis,1,4347,Rafael,Sudeste
3,2025-09-14,Tênis T,Vestuário,3,3046,Ana,Norte
4,2025-08-03,Boné V,Vestuário,2,4453,Bruno,Centro-Oeste

In [4]:
df_vendas = df_vendas.rename(columns={'data': 'data_venda'})

In [5]:
df_vendas.to_csv('/content/vendas.csv', index=False)

In [6]:
df_vendas.head()

,data_venda,produto,categoria,quantidade,preco_unitario,cliente,regiao
0,2025-12-09,Headset G,Periféricos,1,2759,Fernanda,Sudeste
1,2025-03-12,Armário P,Móveis,2,4516,Rafael,Norte
2,2025-11-24,Mesa Escritório N,Móveis,1,4347,Rafael,Sudeste
3,2025-09-14,Tênis T,Vestuário,3,3046,Ana,Norte
4,2025-08-03,Boné V,Vestuário,2,4453,Bruno,Centro-Oeste

In [7]:
import sqlite3

In [13]:
df_vendas.shape[0]

100

In [15]:
conn = sqlite3.connect("/content/vendas.csv")

In [16]:
conn = sqlite3.connect(':memory:')

df_vendas.to_sql("vendas", conn, index = False, if_exists="replace")

100

In [21]:
df_vendas = pd.read_sql_query("SELECT *, quantidade * preco_unitario AS receita_total FROM vendas", conn)

In [22]:
df_vendas.head()

,data_venda,produto,categoria,quantidade,preco_unitario,cliente,regiao,receita_total
0,2025-12-09,Headset G,Periféricos,1,2759,Fernanda,Sudeste,2759
1,2025-03-12,Armário P,Móveis,2,4516,Rafael,Norte,9032
2,2025-11-24,Mesa Escritório N,Móveis,1,4347,Rafael,Sudeste,4347
3,2025-09-14,Tênis T,Vestuário,3,3046,Ana,Norte,9138
4,2025-08-03,Boné V,Vestuário,2,4453,Bruno,Centro-Oeste,8906

In [29]:
#apenas eletrônicos
df_eletronicos = pd.read_sql_query("SELECT * FROM vendas WHERE categoria = 'Eletrônicos'", conn)
df_eletronicos.head()

,data_venda,produto,categoria,quantidade,preco_unitario,cliente,regiao
0,2025-07-24,Tablet D,Eletrônicos,2,4893,Fernanda,Sudeste
1,2025-05-20,Monitor B,Eletrônicos,1,3060,Lucas,Sul
2,2025-06-01,Celular A,Eletrônicos,3,516,João,Centro-Oeste
3,2025-04-22,Celular A,Eletrônicos,2,1018,Fernanda,Nordeste
4,2025-11-24,Notebook X,Eletrônicos,1,2670,Ana,Sul

In [31]:
#mais vendido
df_mais_vendido = pd.read_sql_query("SELECT produto, SUM(quantidade) AS total_vendido FROM vendas GROUP BY produto ORDER BY total_vendido DESC LIMIT 1", conn)
df_mais_vendido.head()

  produto  total_vendido
0  Sofá Q             30

In [33]:
#região com o maior valor de compras
df_regiao = pd.read_sql_query("SELECT regiao, SUM(quantidade * preco_unitario) AS maior_valor FROM vendas GROUP BY regiao ORDER BY maior_valor DESC LIMIT 1", conn)
df_regiao.head()

    regiao  maior_valor
0  Sudeste       245605